// ==========================================================
//  TOPOS
//  Fotos sugeridas en: img/productos/topos/
// ==========================================================
PRODUCTOS.push(
  { id: 57,  nombre: "TOPO CORONA ROLEX SILUETA ROSCA SEGURIDAD", categoria: "Topos", precio: 105000, imagen: "img/productos/topos/1.webp" },
  { id: 58,  nombre: "TOPOS VIRGEN SILUETA ROSCA SEGURIDAD",      categoria: "Topos", precio: 105000, imagen: "img/productos/topos/2.webp" },
  { id: 59,  nombre: "TOPOS VF NEGRO ROSCA SEGURIDAD",            categoria: "Topos", precio: 105000, imagen: "img/productos/topos/3.webp" },
  { id: 60,  nombre: "TOPOS GUCCI ROSCA SEGURIDAD",               categoria: "Topos", precio: 105000, imagen: "img/productos/topos/4.webp" },
  { id: 61,  nombre: "TOPOS OSO TOUS ROSCA SEGURIDAD",            categoria: "Topos", precio: 105000, imagen: "img/productos/topos/5.webp" },
  { id: 62,  nombre: "TOPOS SAN BENITO ROSCA SEGURIDAD",          categoria: "Topos", precio: 105000, imagen: "img/productos/topos/6.webp" },
  { id: 63,  nombre: "TOPOS ROLEX ROSCA SEGURIDAD",               categoria: "Topos", precio: 105000, imagen: "img/productos/topos/7.webp" },
  { id: 64,  nombre: "TOPOS VIRGEN ROSCA SEGURIDAD",              categoria: "Topos", precio: 105000, imagen: "img/productos/topos/8.webp" },
  { id: 65,  nombre: "TOPOS ROLEX HEXAGONO ROSCA SEGURIDAD",      categoria: "Topos", precio: 105000, imagen: "img/productos/topos/9.webp" },
  { id: 66,  nombre: "TOPOS VF DORADO ROSCA SEGURIDAD",           categoria: "Topos", precio: 105000, imagen: "img/productos/topos/10.webp" },
  { id: 67,  nombre: "TOPOS VF ROJO ROSCA SEGURIDAD",             categoria: "Topos", precio: 105000, imagen: "img/productos/topos/11.webp" },
  { id: 68,  nombre: "TOPO VF BLANCO ROSCA DE SEGURIDAD",         categoria: "Topos", precio: 105000, imagen: "img/productos/topos/12.webp" },
  { id: 69,  nombre: "TOPOS ALAS ROSCA SEGURIDAD",                categoria: "Topos", precio: 105000, imagen: "img/productos/topos/13.webp" },
  { id: 70,  nombre: "TOPOS ROLEX MEDIANO ROSCA SEGURIDAD",       categoria: "Topos", precio: 105000, imagen: "img/productos/topos/14.webp" },
  { id: 71,  nombre: "TOPOS CORONA ROLEX",                        categoria: "Topos", precio: 95000,  imagen: "img/productos/topos/63.webp" },
  { id: 72,  nombre: "TOPOS FE GRANDE",                           categoria: "Topos", precio: 90000,  imagen: "img/productos/topos/61.webp" },
  { id: 73,  nombre: "TOPO BALÍN DIAMANTADO",                     categoria: "Topos", precio: 87000,  imagen: "img/productos/topos/27.webp" },
  { id: 74,  nombre: "TOPOS SAN BENITO",                          categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/21.webp" },
  { id: 75,  nombre: "TOPOS VIRGEN GUADALUPE",                    categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/22.webp" },
  { id: 76,  nombre: "TOPOS VIRGEN MILAGROSA",                    categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/23.webp" },
  { id: 77,  nombre: "TOPOS BALIN #5",                            categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/26.webp" },
  { id: 78,  nombre: "TOPOS VF ROJO",                             categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/29.webp" },
  { id: 79,  nombre: "TOPOS VF BLANCO",                           categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/30.webp" },
  { id: 80,  nombre: "TOPOS VF VERDE",                            categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/31.webp" },
  { id: 81,  nombre: "TOPOS VF NEGRO",                            categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/32.webp" },
  { id: 82,  nombre: "TOPOS VF CRISTAL",                          categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/33.webp" },
  { id: 83,  nombre: "TOPOS VF CIRCON CRISTAL",                   categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/34.webp" },
  { id: 84,  nombre: "TOPOS CIRCON COLGANTE DIAMANTADO",          categoria: "Topos", precio: 85000,  imagen: "img/productos/topos/46.webp" },
  { id: 85,  nombre: "TOPOS RAYO",                                categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/16.webp" },
  { id: 86,  nombre: "TOPOS CRUZ PUNTO ESMERALDA",                categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/18.webp" },
  { id: 87,  nombre: "TOPOS CIRCON ARO",                          categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/19.webp" },
  { id: 88,  nombre: "TOPOS CORAZON DOBLE",                       categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/37.webp" },
  { id: 89,  nombre: "TOPOS FLOR PUNTO DIAMANTE",                 categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/53.webp" },
  { id: 90,  nombre: "TOPOS ANGEL",                               categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/55.webp" },
  { id: 91,  nombre: "TOPOS COLGANTE MANO TURCA",                 categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/56.webp" },
  { id: 92,  nombre: "TOPOS PUNTO SERPIENTE",                     categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/57.webp" },
  { id: 93,  nombre: "TOPOS CIRCON VERDE",                        categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/58.webp" },
  { id: 94,  nombre: "TOPOS CIRCON ESMERALDA",                    categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/59.webp" },
  { id: 95,  nombre: "TOPOS ARAÑA CIRCON",                        categoria: "Topos", precio: 80000,  imagen: "img/productos/topos/62.webp" },
  { id: 96,  nombre: "TOPOS ALAS",                                categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/15.webp" },
  { id: 97,  nombre: "TOPOS PUNTO CIRCON",                        categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/17.webp" },
  { id: 98,  nombre: "TOPOS SOL CIRCULAR",                        categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/20.webp" },
  { id: 99,  nombre: "TOPOS GUCCI",                               categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/28.webp" },
  { id: 100, nombre: "TOPOS CARACOL",                             categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/41.webp" },
  { id: 101, nombre: "TOPO PUNTO CIRCON DIAMANTADO",              categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/43.webp" },
  { id: 102, nombre: "TOPO PUNTO CIRCON VERDE",                   categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/45.webp" },
  { id: 103, nombre: "TOPOS FLECHA",                              categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/48.webp" },
  { id: 104, nombre: "TOPOS LUNA CIRCON",                         categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/49.webp" },
  { id: 105, nombre: "TOPOS INFINITO",                            categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/51.webp" },
  { id: 106, nombre: "TOPO MICKEY MOUSE",                         categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/52.webp" },
  { id: 107, nombre: "TOPOS CRUZ PLANA",                          categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/54.webp" },
  { id: 108, nombre: "TOPOS CRUZ CIRCON BLANCO",                  categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/60.jpeg" },
  { id: 109, nombre: "TOPOS CRUZ PUNTO ESMERALDA",                categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/60.jpeg" },
  { id: 110, nombre: "TOPOS SOL CUADRADO",                        categoria: "Topos", precio: 78000,  imagen: "img/productos/topos/64.webp" },
  { id: 111, nombre: "TOPOS BALIN #4",                            categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/25.webp" },
  { id: 112, nombre: "TOPOS CORAZON",                             categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/36.webp" },
  { id: 113, nombre: "TOPOS CORAZÓN PUNTO CIRCON",                categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/38.webp" },
  { id: 114, nombre: "TOPOS CORAZÓN CIRCON",                      categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/39.webp" },
  { id: 115, nombre: "TOPOS CORAL",                               categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/40.webp" },
  { id: 116, nombre: "TOPOS TORTUGA",                             categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/42.webp" },
  { id: 117, nombre: "TOPOS CIRCON ESMERALDA CUADRADO",           categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/44.webp" },
  { id: 118, nombre: "TOPOS HUELLITA",                            categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/47.webp" },
  { id: 119, nombre: "TOPOS AVION",                               categoria: "Topos", precio: 75000,  imagen: "img/productos/topos/50.webp" },
  { id: 120, nombre: "TOPOS BALIN #3",                            categoria: "Topos", precio: 69000,  imagen: "img/productos/topos/24.webp" },
);
